auto: true

markdown: rdiscount
pygments: true
paginate: 20
permalink: /:title

title: iceAnson
url: http://iceAnson.github.io
feed: /atom.xml
author_info: <a href="http://iceAnson.github.io">iceAnson</a>

